### ISSUE TITLE
Support .NET 6 dropped?

### ISSUE THREAD

**Issue by AFAde** [fgilde/MudBlazor.Extensions#10]
Hi, 
My app runs on that version and if I follow the instructions in the README my solution will not compile. Have you completely dropped support of .NET 6? 

Thanks

**Comment by fgilde** [comment]
Currently yes. At this moment you need to use Version 1.6.76 
However I currently work on different compiler options to create a 6.x.x and a 7.x.x package, but one of the problem currently is that I dont know whats the best way for nuget. Because for nuget the highest version is the newest version.

**Comment by mckaragoz** [comment]
@fgilde first of all thanks for the good library.

You can use Mud core logic if you don't use new dotnet 7 features. Mud core supports both dotnet 6 and dotnet 7 in the same release.

**Comment by fgilde** [comment]
I updated all of my libraries to net7 and use them internally. But I will find a solution to bring net6 support back on track.
Currently I'm working on 2 new controls for next version. That means it will take some time but currently version 1.6.76 is identical with the actual version and only net7 upgrade was made. That means at this moment you shouldn't have any problems and for next version I try to find a solution

**Comment by fgilde** [comment]
I found a solution and next version will be compatible with net6 and net7

**Comment by fgilde** [comment]
v 1.7.20 should now work with net7 and net6. Hope everything works in my 2 test projects it looks good. Let me know if there is an issue.
