### ISSUE TITLE
[Bug]: SixLabors.ImageSharp minimum package version upgrade due to security vulnerability

### ISSUE THREAD

**Issue by benjaminalley** [fgilde/MudBlazor.Extensions#100]
### Contact Details

alleyben114@gmail.com

### What happened?

There is a package vulnerability in SixLabors.ImageSharp v3.1.4.

Per Veracode, "SixLabors.ImageSharp [v3.1.4] is vulnerable to an Out-of-bounds Write. The vulnerability is due to minCodeSize in the DecodePixels method within the ImageSharp gif decoder, which allows an attacker to crash the application using a specially crafted gif."

### Expected Behavior

Veracode states that v3.1.5 is currently considered safe and fixes this issue. Fix would be to set minimum required version of SixLabors.ImageSharp to >=3.1.5

### What application type are you referring to?

ServerRendered

### MudBlazor.Extension Version

2.0.2

### MudBlazor Version

7.3.0

### What .net Version are you using?

.Net8

### What browser are you using?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fgilde** [comment]
Thanks for reporting will change it after my vacation asap

**Comment by fgilde** [comment]
Is changed in 2.0.3

**Comment by benjaminalley** [comment]
Thank you for fixing that!
