### ISSUE TITLE
[Bug]: MudExDialog height not adjusting automatically

### ISSUE THREAD

**Issue by APusch-Tenno** [fgilde/MudBlazor.Extensions#106]
### What happened?

hello,

I switched from the standard dialog to the MudEx one, because I needed the ability to drag it.
In my dialog I have a MudTabs element and before the switch the height of the dialog was adjusting automatically depending on different heights of the tabs.
Now it stays at one height and even the dialog buttons are sitting higher and not at the bottom.

![grafik](https://github.com/user-attachments/assets/40570c29-41a6-4f00-9624-2abdceb0bb6b)

My options are:    
`var options = new DialogOptionsEx { DragMode = MudDialogDragMode.Simple, CloseOnEscapeKey = true, MaxWidth = MaxWidth.Medium };`

### Expected Behavior

same behavior as the standard dialog, automatic height adjustment

### What application type are you referring to?

ServerRendered

### MudBlazor.Extension Version

1.7.89

### MudBlazor Version

6.20

### What .net Version are you using?

.Net8

### What browser are you using?

Chrome, Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fgilde** [comment]
You are right. In general it should overwrite this behavior only with specific options like fullheight or resize etc. I will try to fix that.

But however you can easially workaround this by adding a class that contains "height: auto !important" to the dialog class.

```c#
    [Inject]
    MudExStyleBuilder _styleBuilder {get; set;}

    private async Task ShowSampleDialog()
    {
        DialogOptionsEx dlgOptions = new()
        {
            DialogAppearance = MudExAppearance.FromCss(await _styleBuilder.WithHeight("auto").AsImportant().BuildAsClassRuleAsync()),
            MaximizeButton = true,
            CloseButton = true,
            CloseOnEscapeKey = true,
            MaxWidth = MaxWidth.Medium,
            FullWidth = true,
            DragMode = MudDialogDragMode.Simple,
            DisableSizeMarginY = true,
            DisablePositionMargin = true
        };        
        dialogService.ShowEx<SampleDialog>("Simple Dialog", dlgOptions);
    }
```

I've created a sample here: https://try.mudex.org/snippet/cawellazwMfSfQEx

**Comment by APusch-Tenno** [comment]
I have noticed another similar issue, but I'm not sure, if its connected.
This just didn't occur with the standard dialog.

Sporadically the dialog opens up too low, so its title bar is at the middle of the page.
In this case I can just drag the dialog up a bit, but its still annoying.

Just in case this might be related to the workaround or another issue with the dialog itself, I thought to let you know.

**Comment by APusch-Tenno** [comment]
Sorry for being annoying, but I had to switch back to the standard dialog again, because the MudEx one also doesn't adjust its width (for example on a phone or when simply making the browser smaller).

I would have assumed an Extension would retain the original functionalities and just add new ones or extend existing.

**Comment by fgilde** [comment]
Width can changed with the same behavior, however your problem on resize of browser or viewport size is not width related the reason is the position. When using drag or resize dialog is made absolute. However I can easily change or add a setting to use the position as relative % values.

**Comment by APusch-Tenno** [comment]
All I need is the original MudBlazor dialog with the added functionality of dragging it.
If you can make that happen, it would be great.

**Comment by fgilde** [comment]
In general this is exactly the current situation but for drag and resize some css classes and ja style changes are working but it should easy to make them relatively. I will do it for the next version.

**Comment by fgilde** [comment]
this is now done in [MudBlazor.Extensions 2.0.7 Nuget](https://www.nuget.org/packages/MudBlazor.Extensions/2.0.7#readme-body-tab)
