### ISSUE TITLE
Requires a security update

### ISSUE THREAD

**Issue by IngoManthey** [fgilde/MudBlazor.Extensions#107]
### Feature request type

Other

### Is your feature request related to a problem?

The "SixLabors.ImageSharp" 3.1.4 package has a known high severity vulnerability, https://github.com/advisories/GHSA-63p8-c4ww-9cg7.
The "SixLabors.ImageSharp" 3.1.4 package has a known Moderate severity vulnerability, https://github.com/advisories/GHSA-qxrv-gp6x-rc23.
The System.Text.Encodings.Web 4.5.0 package has a known Critical severity vulnerability, https://github.com/advisories/GHSA-ghhp-997w-qr28.

### Describe the solution you'd like

The "SixLabors.ImageSharp" 3.1.4 package has a known high severity vulnerability, https://github.com/advisories/GHSA-63p8-c4ww-9cg7.
The "SixLabors.ImageSharp" 3.1.4 package has a known Moderate severity vulnerability, https://github.com/advisories/GHSA-qxrv-gp6x-rc23.
The System.Text.Encodings.Web 4.5.0 package has a known Critical severity vulnerability, https://github.com/advisories/GHSA-ghhp-997w-qr28.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fgilde** [comment]
We are using SixLabors.ImageSharp 3.1.5

**Comment by IngoManthey** [comment]
@fgilde 
I am using your project https://github.com/fgilde/MudExRichTextEditor. It using 3.1.4.  In version 1.0.9. There do not come a update.

**Comment by fgilde** [comment]
yes thats correct. Its not updated yet I plan to this after I released MudEx 2.0.7 whats planned for Monday or tuesday. Sorry its a lot of work alone in private free time.

**Comment by fgilde** [comment]
I released version 2.0.1 of mudexrichtexteditor
