### ISSUE TITLE
[Bug]: app.UseMudExtensions(); not found

### ISSUE THREAD

**Issue by ProgramGeek02** [fgilde/MudBlazor.Extensions#110]
### Contact Details

l.iovene@assistinformatica.com

### What happened?

I was following the installation guide published [here](https://www.mudex.org/readme#installation) until i face the line that say
"if your are running on Blazor Server side, you should also use the MudBlazorExtensionMiddleware you can do this in your startup or program.cs by adding the following line on your WebApplication"
but when i try to use that command in my program visual studio say that "'WebApplication' does not contain a definition for 'UseMudExtensions' and no accessible extension method 'UseMudExtensions' accepting a first argument of type 'WebApplication' could be found (are you missing a using directive or an assembly reference?)"

Am I really missing something?
My import actually is "MudBlazor.Extensions"

### Expected Behavior

to find the right command

### Screenshots

no screenshot

### What application type are you referring to?

ServerRendered

### MudBlazor.Extension Version

2.0.8

### MudBlazor Version

7.15.0

### What .net Version are you using?

.Net8

### What browser are you using?

Edge

### Sample Solution

No sample solution

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fgilde** [comment]
Because or deprecation of package Microsoft.AspNetCore.StaticFiles and in general no longer support for this kind of http abstractions inside of Microsoft.NET.Sdk.Razor projects I was forced to remove this middleware. This was happen with this [commit](https://github.com/fgilde/MudBlazor.Extensions/commit/49087b1c1ab90237cde2f152e0ad621e2d6716df)

At this point a didn't find an alternative approach. If I do I will add this again. However this only adds a small middleware to set the correct JsRuntime this is something you can easially achieve on your own inside of your Server project where middlewares are fully supported. This is the code you need. Hope that helps, and I'am sorry for that

```c#
public static IApplicationBuilder UseMudExtensions(this IApplicationBuilder builder)
{
    return builder.Use(async (context, next) =>
    {
        var jsRuntime = context.RequestServices.GetRequiredService<IJSRuntime>();
        JsImportHelper.LegacyRuntimeReference = jsRuntime;
        await next();
    });
}
```

**Comment by ProgramGeek02** [comment]
Thanks you for your support.
Have a nice day.


Luca Iovene
Ricerca e sviluppo

[cid:98caf5cc-579f-4322-9cb3-139aa29ee6b6]

T. +39 075 800 10 62
www.assistinformatica.com<http://www.assistinformatica.com>
Avviso sulla tutela di informazioni riservate. Questo messaggio è stato spedito da Assist Informatica s.r.l. Esso e gli eventuali allegati, potrebbero contenere informazioni di carattere estremamente riservato e confidenziale. Qualora non foste i destinatari designati, vogliate cortesemente informarci immediatamente con lo stesso mezzo ed eliminare il messaggio e i relativi eventuali allegati, senza trattenerne copia.

________________________________
Da: Florian Gilde ***@***.***>
Inviato: martedì 3 dicembre 2024 09:57
A: fgilde/MudBlazor.Extensions ***@***.***>
Cc: Luca Iovene ***@***.***>; Author ***@***.***>
Oggetto: Re: [fgilde/MudBlazor.Extensions] [Bug]: app.UseMudExtensions(); not found (Issue #110)


Because or deprecation of package Microsoft.AspNetCore.StaticFiles and in general no longer support for this kind of http abstractions inside of Microsoft.NET.Sdk.Razor projects I was forced to remove this middleware. This was happen with this commit<https://github.com/fgilde/MudBlazor.Extensions/commit/49087b1c1ab90237cde2f152e0ad621e2d6716df>

At this point a didn't find an alternative approach. If I do I will add this again. However this only adds a small middleware to set the correct JsRuntime this is something you can easially achieve on your own inside of your Server project where middlewares are fully supported. This is the code you need. Hope that helps, and I'am sorry for that

public static IApplicationBuilder UseMudExtensions(this IApplicationBuilder builder)
{
    return builder.Use(async (context, next) =>
    {
        var jsRuntime = context.RequestServices.GetRequiredService<IJSRuntime>();
        JsImportHelper.LegacyRuntimeReference = jsRuntime;
        await next();
    });
}
