### ISSUE TITLE
[Bug]: Unable to render PDF Blazor Server Using stream

### ISSUE THREAD

**Issue by syky27** [fgilde/MudBlazor.Extensions#111]
### Contact Details

jump@syky.cz

### What happened?

First of all thanks or this lib!

Trying to render PDF using `MudExFileDisplay`

```csharp
<MudGrid >
    <MudItem xs="6">
        <EntityGrid @ref="Grid" Id="grid-docgen-documents" TEntity="DocGenTableDto" TId="Guid" TCreateCommand="CreateDocGenTable.Command"
                    TUpdateCommand="EditDocGenTable.Command" Context="@Context" Title="@Loc.DOCGEN_DOCUMENT_TABLES">
            <CreateFormContent Context="context">
                <FormDocGenTable Command="context"></FormDocGenTable>
            </CreateFormContent>
            @* <EditFormContent Context="context"> *@
            @*     <FormEditDocGenDocument Command="context"></FormEditDocGenDocument> *@
            @* </EditFormContent> *@
        </EntityGrid>
    </MudItem>
    <MudItem xs="6">

        @if (_loading)
        {
        <MudProgressLinear Color="Color.Secondary" Indeterminate="true" Class="my-7"/>
        }
        else
        {
            if (pdfStream.CanRead)
            {
                <MudExFileDisplay FileName="NameOfYourFile.pdf" ContentType="application/pdf" ContentStream="@pdfStream" ForceNativeRender="true" AllowOpenInNewTab="true"  ></MudExFileDisplay>
            }
                
            @* <iframe *@
            @*     src="@string.Format("data:application/pdf;base64,{0}", pdfString)" *@
            @*     width="100%" *@
            @*     height="100%" *@
            @*     allowfullscreen="true" *@
            @*     title="pdf"> *@
            @*     > *@
            @* </iframe> *@
        }
    </MudItem>
</MudGrid>
```

I am unable to see the pdf in the app, however if I will click on open in new tab, the browser senders the pdf...

<img width="329" alt="Screenshot 2024-12-13 at 4 08 58" src="https://github.com/user-attachments/assets/ae6fa914-b32c-475b-8595-bed99c7010ec" />

using net9 not working in firefox, chromium, safari

Thank you for suggestions

### Expected Behavior

See rendered PDF

### Screenshots

<img width="920" alt="Screenshot 2024-12-13 at 4 02 56" src="https://github.com/user-attachments/assets/4bbc8f0a-53fe-4ecf-8775-e4ca34e07b12" />
<img width="920" alt="Screenshot 2024-12-13 at 4 03 07" src="https://github.com/user-attachments/assets/359ad87c-832a-4219-9f7c-897f6113d640" />

### What application type are you referring to?

ServerRendered

### MudBlazor.Extension Version

2.0.8

### MudBlazor Version

7.15.0

### What .net Version are you using?

.Net8

### What browser are you using?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by syky27** [comment]
I am also not able to render pdf via URL (first pdf I found on google)

```csharp
                <MudExFileDisplay FileName="NameOfYourFile.pdf" ContentType="application/pdf" Url="http://langer.zam.slu.cz/english/FCE-Result-Student%27s-Book.pdf" ForceNativeRender="true" AllowOpenInNewTab="true"  ></MudExFileDisplay>

```

**Comment by syky27** [comment]
Ok, I was able to get it working... There was multiple problems in my implementation...

- Browser was not able to process inline js in the <object> tag

```csharp
      var policy = new HeaderPolicyCollection()
      .AddFrameOptionsDeny()
      .AddContentTypeOptionsNoSniff()
      .AddReferrerPolicyStrictOriginWhenCrossOrigin()
      .AddCrossOriginOpenerPolicy(builder => builder.SameOrigin())
      .AddCrossOriginResourcePolicy(builder => builder.SameOrigin())
      // .AddCrossOriginEmbedderPolicy(builder => builder.RequireCorp()) // remove for dev if using hot reload
      .AddContentSecurityPolicy(builder => {
        builder.AddScriptSrcAttr().Self().UnsafeEval().UnsafeInline();
        builder.AddObjectSrc().UnsafeInline().From("data:").From("blob:");
```

- I am also using nonce, to validate js scrips

```csharp
        builder.AddScriptSrc()
          .WithNonce()
          .Self()
          .UnsafeEval() // due to Blazor WASM
          .StrictDynamic()
          .OverHttps()
          .UnsafeInline(); // only a fallback for older browsers when the nonce is used
```

So I had to do this in my `App.razor`

```csharp
<script nonce="@BlazorNonceService.Nonce" src="_content/MudBlazor.Extensions/js/mudBlazorExtensions.js"></script>
```

Anyways, thanks for lib, sorry for email spam :)

**Comment by fgilde** [comment]
No problem and thanks for sharing this experience 👍

**Comment by syky27** [comment]
@fgilde one more question, any idea whyt I am getting this error only in firefox, but the pdf still loads...

<img width="835" alt="Screenshot 2024-12-14 at 16 14 05" src="https://github.com/user-attachments/assets/8c82d1cb-bc27-492f-bf86-474ee4718acb" />

**Comment by fgilde** [comment]
The native rendering uses an object tag and your Firefox isn't able to display the pdf in an object tag I think. But I can try to test this on my system and then check what options we have. You can test to explicitly uses an iframe instead, the mudexfiledisplay has an option for that

**Comment by syky27** [comment]
@fgilde well i am able to view pdf in firefox in object tag, i dont see option to use iframe...

**Comment by fgilde** [comment]
I think name is FallBackInIframe
