### ISSUE TITLE
[Bug]: Popup Not Closing and Newly Added Item Not Appearing in Edit Form in MudExObjectEditForm

### ISSUE THREAD

**Issue by sreejithishere** [fgilde/MudBlazor.Extensions#112]
### Contact Details

sreejithrkylm@gmail.com

### What happened?

When using the MudExObjectEditForm with an ICollection or List property, the popup does not close after adding a new item. Although the item is successfully added and visible on the screen, the newly added item's value does not appear in the edit form, and the popup remains open.

Steps to Reproduce

Use the example provided in the official GitHub repository.
Set up a form with an ICollection or List property using the provided code snippet.
Add a new item through the popup.
Observe the following issues:
The popup does not close after adding the item.
If I manually inspect the popup and hide with CSS the other issue is when I try to edit the the newly added item’s value it will not appear in the edit form.

### Expected Behavior

1. The popup should close after clicking the close button after adding an item.
2. The value of the newly added item should appear correctly in the edit form.

I have uploaded the solution please see the Index.razor page and try to add an entry to programming skills

### Screenshots

![image](https://github.com/user-attachments/assets/f35de737-a9bf-4160-b97c-2c2d47724611)

### What application type are you referring to?

ServerRendered

### Custom Application Type

Blazor server

### MudBlazor.Extension Version

2.0.8

### MudBlazor Version

7.15.0

### What .net Version are you using?

.Net8

### What browser are you using?

Chrome

### Sample Solution

[BlazorApp3.zip](https://github.com/user-attachments/files/18136443/BlazorApp3.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fgilde** [comment]
Very strange behavior, dont know why its not happened on my page but however i will have a look at it as soon as possible. Sorry

**Comment by fgilde** [comment]
Ok it was related to a thread problem on server side render projects. I fixed that. 
Will be released in 2.0.9 later this day but you should able to test it in the preview package

```<PackageReference Include="MudBlazor.Extensions" Version="2.0.9-prev-2412151234-main" />```

**Comment by sreejithishere** [comment]
I have tested the new version and the issue got resolved. Thank you so much for the quick fix

**Comment by fgilde** [comment]
You're welcome thanks for reporting I didn't have much users who are using server side rendered projects so also a value for me to find and fix these issues
