### ISSUE TITLE
Crashes on startup AddMudExtensions()

### ISSUE THREAD

**Issue by danglingneuron** [fgilde/MudBlazor.Extensions#12]
MudBlazor 6.1.6
MudBlazor.Extensions 1.7.27

Crashes on startup AddMudExtensions()

Unable to load one or more of the requested types.
Method 'get_RenderCompleteTaskCompletionSource' in type 'MudBlazor.Extensions.Core.MudExDialogRef`1' from assembly 'MudBlazor.Extensions, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
![mbextension](https://user-images.githubusercontent.com/12782664/210183300-d429976b-c4ad-47a3-a7f0-f6898e5be759.jpg)

**Comment by Adwelean** [comment]
Same here :/

**Comment by fgilde** [comment]
Is fixed in version 1.7.28. 
Thanks for reporting
