### ISSUE TITLE
Another small layout error

### ISSUE THREAD

**Issue by Adwelean** [fgilde/MudBlazor.Extensions#13]
Hi,

Thanks for your corrections (1.7.28 & .29), I have another layout error, a new div appeared and breaks the full-height css property any idea ?

![image](https://user-images.githubusercontent.com/6142196/210359820-ea9b16c3-1138-4081-8ee1-190b0e28fc5d.png)

MudBlazor : 6.1.7
MudBlazor.Extensions : 1.7.29

**Comment by fgilde** [comment]
Not yet but I will check it asap

**Comment by fgilde** [comment]
Thanks for reporting.
Bug is fixed with 1.7.30 
Because its a new css selector included. Ensure browser cache is cleared or not used.
