### ISSUE TITLE
ObjectEditMeta ReadOnly prefix in MudTextField

### ISSUE THREAD

**Issue by DennisvanZetten** [fgilde/MudBlazor.Extensions#15]
Hi,

Would it be possible to give a string property a readonly prefix?
 I try to achieve the following:

I have two properties:

` meta.Property(m => m.Category)
.WithOrder(1)
.WithLabel(_localizer[LK.TranslationsFormCategory])
.RenderWith<CategorySelect, TranslationCategoryDTO>(c => c.Value)
.WrapInMudItem(i => i.xs = 12); ;

meta.Property(m => m.Key)
.WithOrder(2)
.WithLabel(_localizer[LK.TranslationsFormKey])
.WithAdditionalAttributes<MudTextField<string>>(true, t => t.Variant = Variant.Filled);`

I would like to use the category selected as prefix for the key making them a unique combination. The user can only create the key.
So for example

Selected Category is registration.

The key text shows: registration_XXXXXX where the user can only change the XXXXX
Would this somehow be possible?

Thanks in advance

Dennis

**Comment by fgilde** [comment]
Just for label or description you can use the resolver for label or description and use your Model however you want. 
For editing or whatever you can check if the Mask Property helps.



```csharp
    public TestModel Test { get; set; } = new();


    public class TestModel
    {
        public Gender? Gender { get; set; }
        public string Text { get; set; }
    }

    public enum Gender
    {
        Male,
        Female,
        Other
    }

    private void Configure(ObjectEditMeta<TestModel> meta)
    {

        meta.Property(m => m.Text)
            .WithLabelResolver(i => Test.Gender?.ToString() + "_ Text")
            .WithDescriptionResolver(i => Test.Gender?.ToString())
            .WithAttributesIf<TestModel, MudTextField<string>>(m => m.Gender == Gender.Male, f => f.Mask = new PatternMask("###-##-##"))
            .WithAttributesIf<TestModel, MudTextField<string>>(m => m.Gender == Gender.Female, f => f.Mask = new PatternMask("###-##-##"));
    }
```
