### ISSUE TITLE
Codebeam collaboration

### ISSUE THREAD

**Issue by enkodellc** [fgilde/MudBlazor.Extensions#17]
@fgilde nice work on the components! 

I am not sure if you have seen what @mckaragoz has done with the codebeam Mudblazor extensions but I think it would be great to see them combined.

https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions

I appreciate the knowledge sharing by the community.

**Comment by mckaragoz** [comment]
Thanks.

I noticed the MudBlazor.Extensions before, but after created the CodeBeam library. Has really valuable components. I always talk and suggest about these two library as the most useful and cool ones (except libraries that have one component like Markdown).

At the start, CodeBeam does not planned as a general extension package, i have only seperated projects that has single extension component. But now, CodeBeam library structure significantly improved and designed similar with Mud core, seperated server-side and wasm docs, test and test viewer projects, min.css and min.js etc.

Of course a collaboration makes sense, we can put the components into CodeBeam.

**Comment by enkodellc** [comment]
Very good. I will close this issue and let you two decide on how to collaborate. 

FYI I am the originator of BlazorBoilerplate  https://github.com/enkodellc/blazorboilerplate and [@Gioviq  ](https://github.com/GioviQ)  is my main collaborator. I have not updated in a bit but Gio has. He is a great Blazor / .net freelancer that my company uses so if you need one as well hit him up.
