### ISSUE TITLE
MudExObjectEdit Customize runtime item collection

### ISSUE THREAD

**Issue by franklupo** [fgilde/MudBlazor.Extensions#20]
HI,
I have object with one or more collections.
It is possible to customize dialog size?
It is possible to customize any property of the object contained in the collection?

Best regards

**Comment by fgilde** [comment]
Yes, you can use the MetaConfiguration in general for customize property and behaviours of your model or sub model independent if a dialog from collection edit is used or the form directly. 

Here for exampel if UserModel should be configured to use a password field for the password property

```c#
public class UserModelMetaConfiguration: IObjectMetaConfiguration<UserModel>
{
    public Task ConfigureAsync(ObjectEditMeta<UserModel> meta)
    {
        meta.Properties(m => m.FirstName, m => m.LastName)
            .WrapInMudItem(mudItem => mudItem.xs = 6);
        meta.Property(m => m.Password)
            .RenderWith<MudTextField<string>, string>(field => field.Value, field =>
            {
                field.InputType = InputType.Password;
            })
            .WrapInMudItem(mudItem => mudItem.xs = 12);
        return Task.CompletedTask;
    }
}
```

[Sample](https://mudex.azurewebsites.net/shared-config)


For size or dialog options in general you can set them only to MudExCollectionEdit. That means if the collection is used inside of an editable model you need to specify this as well in the meta configuration, but I will add a possibility to forword from MudExObjectEdit. However you can do currently with a MetaConfoguration as well. 
For Example if you have a class like this with a collection of Users in this case


```c#
public class SomeClassWithUser
{
    
    public List<UserModel> Users { get; set; }
```

You can create you meta config like this

```c#
public class SomeClassWithUserMetaConfiguration : IObjectMetaConfiguration<SomeClassWithUser>
{
    public Task ConfigureAsync(ObjectEditMeta<SomeClassWithUser> meta)
    {
        DialogOptionsEx dialogOptionsEx = new DialogOptionsEx()
        {
            MaximizeButton = true,
            CloseButton = true,
            FullHeight = true,
            CloseOnEscapeKey = true,
            MaxWidth = MaxWidth.Medium,
            FullWidth = true,
            DragMode = MudDialogDragMode.Simple,
            Animations = new[] { AnimationType.SlideIn },
            Position = DialogPosition.CenterRight,
            DisableSizeMarginY = true,
            DisablePositionMargin = true
        };
        meta.Properties(m => m.Users)
            .RenderWith<MudExCollectionEditor<UserModel>, ICollection<UserModel>>(ce => ce.Items)
            .WithAdditionalAttribute(nameof(MudExCollectionEditor<UserModel>.DialogOptions), dialogOptionsEx);

        return Task.CompletedTask;
    }
}
```

**Comment by franklupo** [comment]
Well but it works partly for me.
I have a generic object that I don't know about.
in the Configure(ObjectEditMeta<T> meta) method I apply changes to all my properties, if I change the type of password, fix the label and more. When I encounter a property of type ICollection I apply the modification of the dialog you recommended, but the properties that are displayed in the dialog I don't know how to modify.

How can I do?

Best regards

**Comment by fgilde** [comment]
That should not be a problem. You also can configure the meta. You dont need to use the Configure Method on the MudExObjectEdit component. You can also just implement the IObjectMetaConfiguration interface.

What I'm for example doing is this. I have a base Config for my Dto's

```
public abstract class BaseDtoMetaConfiguration<T, TId> : IObjectMetaConfiguration<T> where T : IDtoBase<TId>
{
    public virtual Task ConfigureAsync(ObjectEditMeta<T> meta)
    {
        meta.Property(x => x.Id)
            .WithAdditionalAttributes(true,new KeyValuePair<string, object>(nameof(MudBaseInput<TId>.Disabled), true))
            .WithOrder(0);
        if (meta.Value.IsNew)
            meta.Property(x => x.Id).Ignore();
        meta.Property(x => x.IsNew).Ignore();
        meta.WrapEachInMudItem(i =>
        {
            i.xs = 12;
            i.md = 6;
        });
        return Task.CompletedTask;
    }
}
```

And then for all my Dtos I create a small config.

```
public class IcdDtoMetaConfiguration: BaseDtoMetaConfiguration<IcdDto, int>
{
    public override Task ConfigureAsync(ObjectEditMeta<IcdDto> meta)
    {
        meta.Property(dto => dto.Name).WrapInMudItem(i => i.md = 12);
        meta.Property(dto => dto.IcdVersion).Ignore();
        return base.ConfigureAsync(meta);
    }
}
```

And then its independent where and why you model is rendered later on, your config will work. 

Also you can configure all Collections inside of a MetaConfig. Independent if youre using the interface or the delegate on the component you can just query your properties and do something for all collections. 

```
    private static bool IsCollection(Type type)
        => type.IsGenericType && type.GetGenericTypeDefinition() == typeof(ICollection<>) || type.GetInterfaces().Any(IsCollection);

meta.AllProperties.Where(oem => IsCollection(oem.PropertyInfo.PropertyType)).RenderWith(...);
```

And if all of this doesnt help, you can also Registering global type defaults with the static class RenderDataDefaults.

```
RenderDataDefaults.RegisterDefault<ICollection<string>, MudExCollectionEditor<string>>(f => f.Items);
```
Then all ICollections of string will be rendered with the desired configuration if no other meta config is provided.
