### ISSUE TITLE
MudGrid support in resizable MudDialog

### ISSUE THREAD

**Issue by dsx20** [fgilde/MudBlazor.Extensions#23]
Is is possible to add MudGrid support in context of a MudDialog.  At present it seems a MudGrid within a MudDialog doesn't react to the dialog being resized.

When trying out the [https://mudblazor.com/components/grid#grid-with-breakpoints](url) example and also applying the resize ability (provided by this MudBlazor.Extensions library) the controls always stay in their original locations.  Only resizing of the main browser document does the MudGrid on the dialog react and subsequently re-layout its controls.

We haven't decided on whether to use the MudGrid or our own flex based solution but would prefer the former approach.  As always we will contribute to this issue should we find a solution ourselves.

**Comment by fgilde** [comment]
You're totally right. This is currently not supported. I try to fix/change this behavior
