### ISSUE TITLE
Out dated Blazored.FluentValidation

### ISSUE THREAD

**Issue by Abdulstar** [fgilde/MudBlazor.Extensions#25]
Using it in new project gives an error when fluent validation is already installed.
![image](https://github.com/fgilde/MudBlazor.Extensions/assets/23205189/dd502625-9ff4-4ade-a9a6-5b2cada83a3a)

**Comment by fgilde** [comment]
I updated all packages to newest version. Will be available today in v1.7.62
![image](https://github.com/fgilde/MudBlazor.Extensions/assets/11070717/1ed86a3d-54db-45fb-978b-3f5ee927139a)
