### ISSUE TITLE
[Bug]: MudExUploadEdit totally breaks application.

### ISSUE THREAD

**Issue by J3ster1337** [fgilde/MudBlazor.Extensions#35]
### What happened?

MudBlazor: 6.8.0
Ex: 1.7.64

When I try to upload files (or even select them), server freezes and after some time this happens:
![image](https://github.com/fgilde/MudBlazor.Extensions/assets/130294475/5c932be4-c8b5-41bb-b13f-2b5109a931a3)
![image](https://github.com/fgilde/MudBlazor.Extensions/assets/130294475/f42972e4-3404-4876-816d-dd885bf786c6)

It happens always besides when I try to upload this one file, but even it breaks everything: 
![image](https://github.com/fgilde/MudBlazor.Extensions/assets/130294475/098ffa00-157f-47b7-b966-b10cb095ac8e)

It saves same way then: 
![image](https://github.com/fgilde/MudBlazor.Extensions/assets/130294475/63d45317-3562-4fd1-849d-cf3a65d63dfa)

My code:

```
	<MudExUploadEdit @bind-UploadRequests="files" MimeTypes="@mimeTypes" T="UploadableFile" Style="height: 400px; max-height: 400px; width: 800px" AllowMultiple="true" />
	<MudButton OnClick="@UploadFiles">upload</MudButton>


@code {
	private string[] mimeTypes =
	{
        "image/*"
    };
	IList<UploadableFile> files;
	private async Task UploadFiles()
	{
		string fileStorage = Configuration.GetValue<string>("FileStorage")!;
		foreach (var file in files)
		{
			Directory.CreateDirectory(Path.Combine(fileStorage, "CARD"));
			string newName = Path.GetRandomFileName(); 
			string newFileName = Path.ChangeExtension(newName, Path.GetExtension(file.FileName));
			string path = Path.Combine(fileStorage, "CARD", newFileName);
			await File.WriteAllBytesAsync(path, file.Data);
		}
	}
```

Edit: I managed to upload one webp file too somehow, but others don't work.

### Expected Behavior

To not freeze

### What browser are you using?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fgilde** [comment]
I will have a look after vacation. Looks like wrong jsruntime is used. But I will fix it. 👍

**Comment by fgilde** [comment]
Ok this is Hard to find out. Fu***.. .. 
However can you confirm that it works if you set AlloweMultiple to false ?

`<MudExUploadEdit @bind-UploadRequests="files" AllowFolderUpload="false" MimeTypes="@mimeTypes" T="UploadableFile" Style="height: 400px; max-height: 400px; width: 800px" AllowMultiple="false" />`

**Comment by fgilde** [comment]
Ok maybe I have fixed it. Can you test with this preview package?
[1.7.65-d2308141158](https://www.nuget.org/packages/MudBlazor.Extensions/1.7.65-d2308141158)

**Comment by J3ster1337** [comment]
Wow thanks!!!! Yes, now any file (or multiple files) can be uploaded without the bug occurring. The library is totally mind-blowing <3

**Comment by fgilde** [comment]
Thanks a lot :-)
