### ISSUE TITLE
[Bug]: FileDisplayZip styles isn't applied until you refresh(?) the component

### ISSUE THREAD

**Issue by J3ster1337** [fgilde/MudBlazor.Extensions#36]
### What happened?

On page load:
![image](https://github.com/fgilde/MudBlazor.Extensions/assets/130294475/8513e681-b707-4f02-bb36-32493e52a93d)

After opening any file preview and then closing it:
![image](https://github.com/fgilde/MudBlazor.Extensions/assets/130294475/8b19bec8-4cc2-4f21-97b3-9bbac27d40b5)

And also, can you please add to documetation that ContentStream field on FileDisplay & FileDisplayZip needs NOT closed/disposed stream?

Thanks a lot for this library! I'm really enjoying it

### Expected Behavior

-

### What browser are you using?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fgilde** [comment]
Do you have an Server side blazor project, or a webassembly app?

**Comment by J3ster1337** [comment]
> Do you have an Server side blazor project, or a webassembly app?

I'm using server

**Comment by fgilde** [comment]
This should work now! 
not released but you can test it with this preview package
[1.7.65-d2308140839](https://www.nuget.org/packages/MudBlazor.Extensions/1.7.65-d2308140839)

**Comment by J3ster1337** [comment]
Thanks a lot! It works perfectly now. :)
