### ISSUE TITLE
need to recompile with the new version of mudblazor

### ISSUE THREAD

**Issue by QianMoXi** [fgilde/MudBlazor.Extensions#4]
Because of https://github.com/MudBlazor/MudBlazor/pull/4639 , the extension cannot run with the new version of mudblazor.

![image](https://user-images.githubusercontent.com/26250460/182097617-529a6c88-aa4a-4e3a-9ca6-948a8264b066.png)

Please update the nuget package dependencies and recompile the release

**Comment by fgilde** [comment]
done 1.3.0
