### ISSUE TITLE
[Bug]: MudExFileDisplay won't load file from Stream

### ISSUE THREAD

**Issue by mreic** [fgilde/MudBlazor.Extensions#43]
### What happened?

I have a Blazor Server with a upload folder where files are uploaded.
If i want to display one of these files from stream using the following command:

`await DialogService.ShowFileDisplayDialog(stream, uploadedFile.uploaded_file_orig_file_name, mimetype, HandleContentError, ex => ex.JsRuntime = JS);`

the display control shows as follows:
![image](https://github.com/fgilde/MudBlazor.Extensions/assets/107549087/10f4bf1a-419d-414f-a1ec-72b95de4d048)

I checked if the stream is available, which it is.

Unfortunately i cannot use the newest version of MudEx because of a bug in MudBlazor since 6.5.

### Expected Behavior

The file should be displayed.

### What application type are you referring to?

Other

### Custom Application Type

Server

### MudBlazor.Extension Version

1.7.61

### MudBlazor Version

6.4.1

### What browser are you using?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fgilde** [comment]
Stream is fully available on client side?
Can you check if it works with a data url for the stream?

`DataUrl.GetDataUrl(stream.ToByteArray())`

That means in your case

```c#
using Nextended.Blazor.Models;
...

await dialogService.ShowFileDisplayDialog(DataUrl.GetDataUrl(stream.ToByteArray()), uploadedFile.uploaded_file_orig_file_name, mimetype, HandleContentError, ex => ex.JsRuntime = JS);
```

**Comment by mreic** [comment]
What do you mean by "fully available on client side"? 
File is stored on the servers filesystem.

Testing as follows:
![image](https://github.com/fgilde/MudBlazor.Extensions/assets/107549087/eb2ff689-42bc-49dd-9569-cb42d2e0bb3f)

This test does not work. 
If you uncomment the bytes-assignment and the second dialog call and comment out the first dialog call you can open small files. Large files get an "URI too Long"-Exception.

**Comment by fgilde** [comment]
Ok understand. I also fixed stream handling but that doesnt help you at all. Because for native file display (That means without custom IMudExFileDisplay implementation like Zip or Markdown handling) also a is created from stream because depending on mimetype iframe, img tag or object tags are used and they need a url

**Comment by fgilde** [comment]
if youre files came from server and I would have you problems I would ensure to have a url for the file itself.
For example if you have your files in a database (or whatever) i would create a Controller to read the files.
I mean like this

```c#
using Microsoft.AspNetCore.Mvc;

[Route("api/[controller]")]
[ApiController]
public class FileController : ControllerBase
{
    private readonly IFileRepo _fileRepo;

    public FileController(IFileRepo fileRepo)
    {
        _fileRepo = fileRepo;
    }

    [HttpGet("{id}")]
    public IActionResult GetFileById(string id)
    {
        byte[] fileData = _fileRepo.GetFile(id);
        if (fileData == null || fileData.Length == 0)
        {
            return NotFound();
        }

        return File(fileData, "application/octet-stream"); // Set the appropriate MIME type if you know it.
    }
}

```

than you can use a url like `api/file/123` 

Hope that helps a bit.

**Comment by fgilde** [comment]
Thank you very much for sharing this bug, i fixed it and it will released in 1.7.68 you can have a look at preview package [1.7.68-prev-2309141720-main](https://www.nuget.org/packages/MudBlazor.Extensions/1.7.68-prev-2309141720-main)

also you can see it running here https://mudex.azurewebsites.net/handle-file-as-streams (all files here are set as stream see code)

Would you explain why you cant update MudBlazor to 6.9 ?

**Comment by mreic** [comment]
I'll test it tomorow..
Thank you in advance!

I cant Upgrade because of a Bug i reported in MudBlazor (https://github.com/MudBlazor/MudBlazor/issues/7237).
I use exactly that combination of options in MudDataGrid and unfortunately nobody is responding at this time.. but we will see. I personally cant find a working workaround for this so i am Stuck with this Version for the moment.

**Comment by fgilde** [comment]
I created a compatible package with MudBlazor 6.4.1 for you. Hope that helps. 
If it does please close this issue.

[1.7.68-prev-2309150848-for-mudblazor-6.4.1.](https://www.nuget.org/packages/MudBlazor.Extensions/1.7.68-prev-2309150848-for-mudblazor-6.4.1)

**Comment by mreic** [comment]
Thanks for the Package!
It helps for mostly all use-cases. Mostly, because i experienced that larger PDF-Files are not loaded.
They can be downloaded, but the preview pane keeps empty.

Any Idea on this?

Update:
It seems that i can update my project to something above 6.4.1 because somebody posted a workarround. I need to do some testing to validate this.

**Comment by mreic** [comment]
While further testing it seems that the file display components dont dispose properly. May be that its my code doing sth wrong, but RAM-usage increases on every dialog call and stays up even when GC takes place.

Sorry for asking so many questions ;)

**Comment by fgilde** [comment]
No problem your welcome.

For question 1: Pdf and all other native display files like image etc where tag is used needs an url, and maybe your pdf is to big for a data url. I guess you need to playaround with it, or if you can provide a sample pdf I will have a look if I can do something.

For question 2: Stream is currently not disposed on component side because I dont want to close given streams because this can cause side effects. (However for MudExFileDisplayZip they are copied and maybe I need to rethink about disposing given streams )

**Comment by mreic** [comment]
For your first answer:
I once build a simple file preview (mostly only pdf and images) facing the nearly same problem with larger files. I found a way to do this using following function in "_host.cshtml" :

```javascript
window.openFileFromStream = async (fileName, contentStreamReference, fileType) => {
    const arrayBuffer = await contentStreamReference.arrayBuffer();
    const blob = new Blob([arrayBuffer], { type: fileType });
    const url = URL.createObjectURL(blob);
    //document.querySelector("embed").src = url;

    const elem = document.getElementById("preview-element");
    if(elem != null){
        elem.src = url;
        await new Promise(resolve => setTimeout(resolve, 1000));
        URL.revokeObjectURL(url);
    }
    else{
        URL.revokeObjectURL(url);
    }

}
``` 

I personally dont know if its a nearly clean idea to get rid of the file size issue. Maybe you can check?

Second answer:
I am using this call:
```c#
string mimetype = Utilities.Utilities.GetMimeType(uploadedFile.uploaded_file_orig_file_name);

//await DialogService.ShowFileDisplayDialog($"https://localhost:1235/api/file/{uploadedFile.uploaded_file_id}", uploadedFile.uploaded_file_orig_file_name, mimetype, HandleContentError, ex => ex.JsRuntime = JS);

using (Stream stream = GetFileStream(uploadedFile))
{
    await DialogService.ShowFileDisplayDialog(stream, uploadedFile.uploaded_file_orig_file_name, mimetype, HandleContentError, ex => ex.JsRuntime = JS);
}
``` 
Seeing the code i would expect the stream to get closed and als release resources. Is there any possibilities for your component to keep data that was read from stream?

**Comment by fgilde** [comment]
Can you test this package? [1.7.68-prev-2309182049-stre...](https://www.nuget.org/packages/MudBlazor.Extensions/1.7.68-prev-2309182049-stream-and-blob)

You can now set url handling to blob the MudExFileDisplay has now a Parameter for that called `StreamUrlHandling`
If you use a dialog you can set it like this

```c#
    private async Task OpenAsDialog()
    {
        var parameters = new DialogParameters {
            { nameof(MudExFileDisplay.StreamUrlHandling), StreamUrlHandling.BlobUrl }
        };
        await dialogService.ShowFileDisplayDialog(SampleFile.Stream, SampleFile.Name, SampleFile.ContentType, HandleContentError, null, parameters);
    }```

**Comment by mreic** [comment]
Thank you for your always fast replies!
Larger PDF work now! Unfortunatly .zip-files now are broken.
![image](https://github.com/fgilde/MudBlazor.Extensions/assets/107549087/1c9e6868-36d7-4708-acdc-6005ed0c3203)

The error is the same on calling the Dialog without the parameters.

**Comment by fgilde** [comment]
The zip and info bug reproducible should be enough. You have a server side rendered project? Maybe there is the difference. Because in my sample https://mudex.azurewebsites.net/handle-file-as-streams it works well

**Comment by mreic** [comment]
Yes, my project is rendered server side. I tried to open following zip: 
[open3A 3.8.zip](https://github.com/fgilde/MudBlazor.Extensions/files/12660728/open3A.3.8.zip)

Dialog starts showing the loading spinner while the debugger prints the error from the screenshot posted earlier ("Cannot access a closed stream)

Dialog call is exacly like you suggested:

Your code:
```c#
private async Task OpenAsDialog()
    {
        var parameters = new DialogParameters {
            { nameof(MudExFileDisplay.StreamUrlHandling), StreamUrlHandling.BlobUrl }
        };
        await dialogService.ShowFileDisplayDialog(SampleFile.Stream, SampleFile.Name, SampleFile.ContentType, HandleContentError, null, parameters);
    }
``` 
My code:
```c#
private async Task OpenAsDialog(UploadedFileModel uploadedFile)
{
    //DialogOptionsEx options = new DialogOptionsEx() { JsRuntime = JS};

    //Stream stream = null;
    try
    {
        string mimetype = Utilities.Utilities.GetMimeType(uploadedFile.uploaded_file_orig_file_name);

        //await DialogService.ShowFileDisplayDialog($"https://localhost:1235/api/file/{uploadedFile.uploaded_file_id}", uploadedFile.uploaded_file_orig_file_name, mimetype, HandleContentError, ex => ex.JsRuntime = JS);

        var parameters = new DialogParameters {
            { nameof(MudExFileDisplay.StreamUrlHandling), StreamUrlHandling.BlobUrl }
        };

        using (Stream stream = GetFileStream(uploadedFile))
        {
            await DialogService.ShowFileDisplayDialog(stream, uploadedFile.uploaded_file_orig_file_name, mimetype, HandleContentError, ex => ex.JsRuntime = JS, parameters);
            //await DialogService.ShowFileDisplayDialog(stream, uploadedFile.uploaded_file_orig_file_name, mimetype, HandleContentError, ex => ex.JsRuntime = JS);
        }
    }
    catch(Exception e)
    {
        Console.Write(e.ToString());
    }

}
```

Hope this helps ;)

**Comment by fgilde** [comment]
Sorry for Late answering today i was not at home. I see your problem. Your scope is finished to early because you are await the show of the dialog only what returns a IDialogReference from MudBlazor if you want to await the closeing to ensure dispose afterwards you need to await the result of the IDialogRefeference

```c#
       using (var stream = SampleFile.Stream) {
           var res = await dialogService.ShowFileDisplayDialog(stream, SampleFile.Name, SampleFile.ContentType, HandleContentError, null, parameters);
           await res.Result;
       }
```

**Comment by mreic** [comment]
Thanks for the Explanation!
Seems like everything is working right now.
