### ISSUE TITLE
[Bug]: Dialog flickers before actual showing animation

### ISSUE THREAD

**Issue by mreic** [fgilde/MudBlazor.Extensions#47]
### What happened?

Project is a Blazor Server.
When opening a dialog with basic settings from mudex.org, dialog first shows with zoom transition, disappears and then shows again with actual configured animation.

Code looks as follows:
```c#
public DialogOptionsEx Options { get; set; } = new()
    {
        MaximizeButton = true,
        CloseButton = true,
        FullHeight = true,
        CloseOnEscapeKey = true,
        MaxWidth = MaxWidth.Medium,
        FullWidth = true,
        DragMode = MudDialogDragMode.Simple,
        Animations = new[] { AnimationType.SlideIn },
        Position = DialogPosition.CenterRight,
        DisableSizeMarginY = true,
        DisablePositionMargin = true
    };

public async Task OpenMudExDialog()
{
    await Task.Delay(1000);
    IDialogReference dlgReference = await DialogService.ShowEx<DlgYesNoPrompt>("Simple Dialog", dialog => { dialog.ContentText = "Hello from dialog sample page"; }, Options);
}
```

### Expected Behavior

Dialog should not be shown using the MudBlazor standard animation before getting shown correctly

### What application type are you referring to?

ServerRendered

### MudBlazor.Extension Version

1.7.68-prev-2309182049-stream-and-blob

### MudBlazor Version

6.10.0

### What browser are you using?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fgilde** [comment]
Just add the class `mud-ex-dialog-initial` on your dialog 

```c#
<MudDialog Class="mud-ex-dialog-initial">
   <TitleContent>
  .... 
 ....
</MudDialog>
```

**Comment by mreic** [comment]
Well, reading the docs properly would have helped! Sorry and Thanks!

**Comment by mreic** [comment]
The Class helps, but behaviour is the same as described always the first time a Dialog is opened

**Comment by fgilde** [comment]
Can you try to load styles manually 

`<link id="mudex-styles" href="_content/MudBlazor.Extensions/mudBlazorExtensions.min.css" rel="stylesheet"> `


To then prevent extra loading you should disable automatic css loading in service configuration 

`builder.Services.AddMudServicesWithExtensions(c => c.WithoutAutomaticCssLoading()); `

**Comment by mreic** [comment]
That solves it! Thanks!
