### ISSUE TITLE
Loading icon for files while uploading

### ISSUE THREAD

**Issue by charlied57** [fgilde/MudBlazor.Extensions#56]
### Feature request type

Enhance component

### Component name

MudExUploadEdit

### Describe the solution you'd like

When you upload a larger file or upload many files the component "hangs" and there is no update that the files are being added to the component. Users may try to re-upload because of no visual indication. Maybe the file can show up as soon as it is added then instead of the rename/delete icons it has a loading wheel until it is finished?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fgilde** [comment]
I will implement this

**Comment by fgilde** [comment]
Not yet released but you can see current state on https://mudex.azurewebsites.net/upload-edit
