### ISSUE TITLE
[Bug]: MudExPopover does not appear to properly dispose of JS click event listener when re-rendering the component

### ISSUE THREAD

**Issue by Swepps** [fgilde/MudBlazor.Extensions#59]
### Contact Details

osgood.george@gmail.com

### What happened?

I have a table where each cell uses a MudExPopover for editing the cell value.
I noticed that if the parameters on the page have changed several times, then the page begins to behave very slowly.

I've tracked this issue down to the MudExPopover and the fact that each time the component re-renders, more and more click event listeners are getting added to the document.

I have enabled 'DisposeEvent' on the component but that doesn't appear to solve the issue, in fact it only serves to cause the following error to appear in the browser log each time the popover component is rendered:
`Uncaught (in promise) Error: System.ArgumentException: There is no tracked object with id '7'. Perhaps the DotNetObjectReference instance was already disposed. (Parameter 'dotNetObjectId')
   at Microsoft.JSInterop.JSRuntime.GetObjectReference(Int64 dotNetObjectId)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson)
    at kt.endInvokeDotNetFromJS (blazor.server.js:1:3700)
    at blazor.server.js:1:72077
    at Array.forEach (<anonymous>)
    at kt._invokeClientMethod (blazor.server.js:1:72063)
    at kt._processIncomingData (blazor.server.js:1:70105)
    at connection.onreceive (blazor.server.js:1:64508)
    at o.onmessage (blazor.server.js:1:48842)`

Refreshing the page solves the problem as all of the JS events will be cleared.

Using the command `getEventListeners(document);` in the browser console shows that the list of 'click' listeners increases with each render of the popover.

### Expected Behavior

Disposing of a MudExPopover component should be properly disposing the JS click event.

### Screenshots

Screenshot of browser log error
![image](https://github.com/fgilde/MudBlazor.Extensions/assets/5452934/f5c2d43a-0851-4fba-bd7c-e80c9f4858de)

Screenshot of usage of MudExPopover in code
![image](https://github.com/fgilde/MudBlazor.Extensions/assets/5452934/7b26a41e-b3b1-479d-a7d4-f3b588ec90fa)

Screenshot of JS function adding click event listener
![image](https://github.com/fgilde/MudBlazor.Extensions/assets/5452934/963f6b27-a56d-4cac-b1e8-c17f0bd85751)

### Reproduction link

https://trymudex.azurewebsites.net/snippet/wkQHvbEwoRUrrWnK

### What application type are you referring to?

ServerRendered

### MudBlazor.Extension Version

1.7.75

### MudBlazor Version

6.11.0

### What browser are you using?

Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Swepps** [comment]
I've been doing a bit more digging. Could it perhaps be caused by BlazorJsEventInterop? It appears to be adding event listeners but doesn't remove them when DotNetObjectReference is disposed.

I found this StackOverflow question which describes a similar issue: [Link](https://stackoverflow.com/questions/70603943/calling-javascript-from-blazor-how-to-dispose-javascript-within-dotnetobjectref)

**Comment by fgilde** [comment]
Thanks for reporting. I will have a look on it.

**Comment by fgilde** [comment]
I've fixed the issue. Will be released in 1.7.76.
You can test it with the preview package [1.7.76-prev-2311022342-main](https://www.nuget.org/packages/MudBlazor.Extensions/1.7.76-prev-2311022342-main)

Please ensure browser scripts are not cached when testing it. For example use incognito tab

**Comment by Swepps** [comment]
Perfect. That's solved our issue completely. Thank you very much :)

**Comment by fgilde** [comment]
you're welcome.
