### ISSUE TITLE
[Bug]: MudExUploadEdit Crashes Dialogs

### ISSUE THREAD

**Issue by tnruff** [fgilde/MudBlazor.Extensions#61]
### Contact Details

tomnruff@gmail.com

### What happened?

Created a MudDialog containing only a MudExUploadEdit. Upon trying to open said dialog, the screen darkens as if a dialog was opened, but nothing renders. Tried testing with another component (Mud DataGrid) within the dialog, same issue. Removing the MudExUploadEdit and just leaving the DataGrid made the dialog render correctly. The MudExUploadEdit uses the following definition (also included in screenshots):
```
<MudExUploadEdit MimeTypes="@mimeTypes" TextDropZone="Drop Files Here or Click Upload Files" T="UploadableFile"
                 DropZoneClickAction="DropZoneClickAction.UploadFile" ShowFileUploadButton="false" @ref="component" MinHeight="68"
                 AllowFolderUpload="false" AllowExternalUrl="false" Style="border: grey 3px dashed;" AllowRename="true"
                 ShowProgressForLoadingData="true" ColorizeIcons="true">
</MudExUploadEdit>
//Which has MudExUploadEdit<UploadableFile> component; and a string[] of valid mimeTypes in the code block.
```

### Expected Behavior

The dialog should display the MudExUploadEdit, either alone or with another component within the dialog.

### Screenshots

![image](https://github.com/fgilde/MudBlazor.Extensions/assets/46604112/ccb15721-2578-415e-afda-5560a1079e17)

### What application type are you referring to?

ServerRendered

### MudBlazor.Extension Version

1.7.76

### MudBlazor Version

6.11.0

### What browser are you using?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fgilde** [comment]
Can you try to create a sample app with this problem?

**Comment by tnruff** [comment]
Sorry for the delay, seems that a hard reboot on the PC worked to fix the issue. Didn't see any improvement through restarts last week but after leaving it off for the weekend it works flawlessly.
