### ISSUE TITLE
Callback for when data is available for files in MudExUploadEdit

### ISSUE THREAD

**Issue by JaronMLifsey** [fgilde/MudBlazor.Extensions#62]
### Feature request type

Enhance component

### Component name

MudExUploadEdit

### Is your feature request related to a problem?

Before the latest release, UploadRequestsChanged would be called when data for files was available. Now, the files appear immediately with loading symbols, and UploadRequestsChanged is called before the data is available. I like the loading symbols, but there's no way of knowing when the data is available now.

### Describe the solution you'd like

Another callback for when files have available data.

### Have you seen this feature anywhere else?

Prior versions of this component.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fgilde** [comment]
Sure I can add an extra callback. If you need the old funcionality you can turn `LoadFileDataBytesInBackground` to false

**Comment by fgilde** [comment]
Will be available in 1.7.77 preview package is available here [1.7.77-prev-2311091211-main](https://www.nuget.org/packages/MudBlazor.Extensions/1.7.77-prev-2311091211-main)
