### ISSUE TITLE
[Bug]: Validation fails on any amount of files

### ISSUE THREAD

**Issue by tnruff** [fgilde/MudBlazor.Extensions#66]
### Contact Details

tomnruff@gmail.com

### What happened?

A form with a MudExUploadEdit with the attribute Required=true will not successfully validate even with files added. Attempting to submit will just mark the field "This field is required."

### Expected Behavior

The form successfully will validate with one or more files in the component.

### What application type are you referring to?

ServerRendered

### MudBlazor.Extension Version

1.7.76

### MudBlazor Version

6.11.0

### What browser are you using?

Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fgilde** [comment]
Are you using MudExUploadEdit inside of a MudForm or are you using it with MudExObjectEditForm ?

**Comment by tnruff** [comment]
Inside a MudForm. The issue was fixed with a prior pull request in the last version but it seems to have been reverted for some reason.

**Comment by fgilde** [comment]
Ok I will have a look. In general it's nothing changed there but I will check it
