### ISSUE TITLE
[Bug]: Component JS loading does not respect App Base Path

### ISSUE THREAD

**Issue by s-summers** [fgilde/MudBlazor.Extensions#67]
### What happened?

For an application with the app base path [configured](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-8.0&tabs=visual-studio#configure-the-app-base-path)

When a page with a MudBlazor.Extensions component loads it does not include the path base
Example: https://localhost:44354/_content/MudBlazor.Extensions/js/components/MudExSplitter.min.js

This is a problem for my deployed app as it runs into a CORS error.

I believe the issue is just a missing `.` prefix to make the path relative
https://github.com/fgilde/MudBlazor.Extensions/blob/ddac23612f6c1844d6d14a07e8271310e94aa5d7/MudBlazor.Extensions/Helper/JsImportHelper.cs#L66-L69

### Expected Behavior

component JS url path should include the configured path base

With a path base of `/mybase/path/`
Expected: https://localhost:44354/mybase/path/_content/MudBlazor.Extensions/js/components/MudExSplitter.min.js

### What application type are you referring to?

WebAssembly

### MudBlazor.Extension Version

1.7.77

### MudBlazor Version

6.11.1

### What browser are you using?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fgilde** [comment]
Thanks for reporting this. I will have a look 👍

**Comment by fgilde** [comment]
Should be fixed in [MudBlazor.Extensions 1.7.78 Nuget](https://www.nuget.org/packages/MudBlazor.Extensions/1.7.78#readme-body-tab)

If the adding '.' change is not enough for you, you can now also specify for custom base path with
```
builder.Services.AddMudServicesWithExtensions(c => c.WithJsBasePath("/yourfolder/_content/"));
```
