### ISSUE TITLE
[Bug]: Unable to add spaces in filter bar of MudExSelect

### ISSUE THREAD

**Issue by JillMaven** [fgilde/MudBlazor.Extensions#74]
### What happened?

It looks like you can't add spaces in the filter bar of the MudExSelect. Pressing spacebar send your cursor to the end of the line and then write a " ".

### Expected Behavior

It should add the space where the cursor is, not a the end of the line

### Screenshots

![image](https://github.com/fgilde/MudBlazor.Extensions/assets/97290012/b63fe091-4811-4503-881c-3fe9b8098d96)

### Reproduction link

mudex.org/mud-ex-select

### What application type are you referring to?

WebAssembly

### MudBlazor.Extension Version

1.7.86

### MudBlazor Version

6.18.0

### What .net Version are you using?

.Net8

### What browser are you using?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fgilde** [comment]
Thanks for reporting. Will fix it as soon as possible

**Comment by fgilde** [comment]
Its fixed. Currently not released yet but can tested in preview package [1.7.87-prev-2404011345-main](https://www.nuget.org/packages/MudBlazor.Extensions/1.7.87-prev-2404011345-main) or higher

Please test it if you have time.  Also demo is updated here https://mudex.azurewebsites.net/mud-ex-select

**Comment by fgilde** [comment]
sorry for late response. currently a lot thinks to do. I have allready started working on it. will fix it as soon as possible

**Comment by fgilde** [comment]
I've releasend an improved version. The select all behavior is still the same. I would expect that. However we can maybe add a new parameter to control the behavior. Please create a suggestion for that.
