### ISSUE TITLE
Dialog cancel event handler - cancable event 

### ISSUE THREAD

**Issue by qisbic** [fgilde/MudBlazor.Extensions#85]
### Feature request type

Enhance component

### Is your feature request related to a problem?

Please refer to discussion "Dialog cancel event handler #83"

"Ok understand. Can you create a feature request issue for that, then I will try add this , but you can also currently do this. Just set closable in the dialogOptions to false and add an own custom close button like the test alarm button, but i will try to implement an cancable event in the ÌDialogEventService`"

### Describe the solution you'd like

Note: This would be useful when users want to close the dialog and ask if they want to save the current changes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fgilde** [comment]
It's done. [MudBlazor.Extensions 1.7.88 Nuget](https://www.nuget.org/packages/MudBlazor.Extensions/1.7.88#readme-body-tab)

A demo can be found here https://www.mudex.org/dialogs-closing-event
Ensure browser cache for js files is empty otherwise demo maybe not work
