### ISSUE TITLE
[Bug]: ReflectionTypeLoadException with Mudblazor 7.0.0 

### ISSUE THREAD

**Issue by gleIsocom** [fgilde/MudBlazor.Extensions#91]
### What happened?

I have tried to use Mudblazor.Extension with the current Mudblazor version 7.0. This error occurs at startup.

### Expected Behavior

No Exception

### Screenshots

![image](https://github.com/fgilde/MudBlazor.Extensions/assets/165257173/def5481b-a7b1-4188-8b67-5071fb9e735a)

### What application type are you referring to?

WebAssembly

### MudBlazor.Extension Version

1.7.89.0

### MudBlazor Version

7.0

### What .net Version are you using?

.Net8

### What browser are you using?

Chrome, Edge, Other

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by fgilde** [comment]
For mudblazor 7 you need to use the currently not released version 2.
A preview is available on nuget https://www.nuget.org/packages/MudBlazor.Extensions/2.0.0-prev-2407041714-for-mudblazor-7.0.0

**Comment by gleIsocom** [comment]
Thanks, I didn't know.
