### ISSUE TITLE
[Bug]: Value cannot be null. (Parameter 'jsRuntime')

### ISSUE THREAD

**Issue by gleIsocom** [fgilde/MudBlazor.Extensions#92]
### What happened?

I have created a Blazor WebAssembly testapp under net7, integrated MudBlazor and added MudBlazor.Extensions and want to display a sample dialog. No matter what I try, I always get the same error. 

### Expected Behavior

No Exceptions

### Screenshots

![image](https://github.com/fgilde/MudBlazor.Extensions/assets/165257173/07f786a4-463d-4bd0-b5ec-5f071681bb28)

### What application type are you referring to?

WebAssembly

### MudBlazor.Extension Version

1.7.89

### MudBlazor Version

6.20.0

### What .net Version are you using?

.Net7

### What browser are you using?

Chrome, Edge

### Sample Solution

[BlazorApp22.zip](https://github.com/user-attachments/files/16107762/BlazorApp22.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mreic** [comment]
Have you tried passing jsRuntime as a parameter to the dialog?

First you inject jsRuntime:
```c#
[Inject] public IJSRuntime? js {get; set;}
```
Then use it in the DialogOptionsEx class:
```c#
 DialogOptionsEx options = new DialogOptionsEx() { JsRuntime = js};

 var dialog = await DialogService.ShowEx<SampleType>("DocTitle", parameters, options);
```

**Comment by fgilde** [comment]
For an web assembly app you can still inject the IJSRuntime in your MainLayout for example and call

`jsRuntime.InitializeMudBlazorExtensionsAsync()`
