### ISSUE TITLE
[Bug]: Clicking backdrop when 'BackdropClick = false' still closes dialog

### ISSUE THREAD

**Issue by jaypalexa** [fgilde/MudBlazor.Extensions#97]
### What happened?

I upgraded to MudBlazor.Extensions v2.0.0 and changed the DialogOptionsEx option on an existing call from `DisableBackdropClick = true` to `BackdropClick = false` as per the MudBlazor v7 migration instructions.

When I clicked on the backdrop when the dialog was open, the dialog closed (and the shaded overlay remained, preventing interaction with the screen beneath it).

ref: [MudBlazor v7.0.0 Migration Guide](https://github.com/MudBlazor/MudBlazor/issues/8447)

### Expected Behavior

I expected that when I clicked on the backdrop when a dialog was open that nothing would happen; that is, that the dialog would remain open.

### What application type are you referring to?

ServerRendered

### MudBlazor.Extension Version

2.0.0

### MudBlazor Version

7.1.1

### What .net Version are you using?

.Net8

### What browser are you using?

Chrome

### Sample Solution

[TestApp.zip](https://github.com/user-attachments/files/16196635/TestApp.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fgilde** [comment]
Thanks I will fix it after my vacation. Thanks for reporting

**Comment by fgilde** [comment]
So I used the mac book from my wife and created a fix.

Its fixed in 2.0.2 https://www.nuget.org/packages/MudBlazor.Extensions/2.0.2

**Comment by jaypalexa** [comment]
All working for me here now, many thanks.  You have gone above and beyond.  Enjoy your vacation!
